import * as vscode from 'vscode';
import assert from 'node:assert/strict';
import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {CommentService, captureAnchor} from '@sideband-comments/core';
import {JsonlThreadRepository} from '@sideband-comments/jsonl-store';

export async function run() {
  const passed: string[] = [];
  const folders = vscode.workspace.workspaceFolders!;
  const fixtures = [];
  for (const folder of folders) {
    const repository = new JsonlThreadRepository(folder.uri.fsPath);
    const service = new CommentService(repository,{actor:()=>({id:'fixture',name:'Fixture'}),id:randomUUID,now:()=>new Date().toISOString()});
    const uri = vscode.Uri.joinPath(folder.uri,'note.txt');
    const text = 'First anchor line\nSecond anchor line\nThird anchor line\n';
    await writeFile(uri.fsPath,text);
    const open = await service.create({documentPath:'note.txt',anchor:captureAnchor(text,0,17),body:folder.name+' open'});
    const resolved = await service.create({documentPath:'note.txt',anchor:captureAnchor(text,18,36),body:folder.name+' resolved'});
    await service.resolve(resolved.id);
    const nested = vscode.Uri.joinPath(folder.uri, 'src', 'lib', 'example.ts');
    await mkdir(vscode.Uri.joinPath(folder.uri, 'src', 'lib').fsPath, {recursive:true});
    await writeFile(nested.fsPath, text);
    await service.create({documentPath:'src/lib/example.ts',anchor:captureAnchor(text,0,17),body:'nested comment'});
    fixtures.push({uri,repository,service,open,resolved});
  }
  const api = await vscode.extensions.getExtension('insung.sideband-comments-vscode')!.activate();
  const {comments,tree,detail} = api;
  const [a,b] = fixtures;
  const editor = await vscode.window.showTextDocument(a.uri);
  await comments.reloadActive('host test');
  const loaded = () => comments.byDocument.get(a.uri.toString());
  const original = loaded().get(a.open.id);
  await new Promise(resolve => setTimeout(resolve, 300));
  original.collapsibleState = vscode.CommentThreadCollapsibleState.Expanded;
  for(let i=0;i<20;i++) await comments.reloadActive('repeat focus');
  assert.equal(loaded().get(a.open.id),original);
  assert.equal(original.collapsibleState,vscode.CommentThreadCollapsibleState.Expanded);
  passed.push('20 reloads preserve native object and expanded state');
  await comments.syncActive({document:{uri:vscode.Uri.parse('comment://sidebandComments/input.md')}});
  detail.selectUri(vscode.Uri.parse('comment://sidebandComments/input.md'));
  assert.equal(loaded().get(a.open.id),original);
  assert.equal(detail.selected.uri.toString(),a.uri.toString());
  passed.push('comment input editor focus preserves native thread and details');
  await a.service.reply(a.resolved.id,'external reply');
  await comments.reloadActive('external write');
  assert.equal(loaded().get(a.open.id),original);
  assert.equal(loaded().get(a.resolved.id).comments.length,2);
  passed.push('external reply updates changed thread and preserves unrelated thread');
  const file=a.repository.threadFile(a.open.id);
  const lines=async()=> (await readFile(file,'utf8')).trim().split('\n').length;
  const before=await lines();
  await Promise.all([comments.submit({thread:original,text:'exactly once'}),comments.submit({thread:original,text:'exactly once'})]);
  await comments.reloadActive('watcher duplicate');
  assert.equal(await lines(),before+1);
  assert.equal(loaded().get(a.open.id),original);
  passed.push('concurrent reply submissions and watcher reload append exactly one event');
  const draft=comments.controller.createCommentThread(a.uri,new vscode.Range(2,0,2,17),[]);
  draft.collapsibleState=vscode.CommentThreadCollapsibleState.Expanded;
  await comments.submit({thread:draft,text:'native draft'});
  assert.equal(loaded().get(comments.idFor(draft)),draft);
  assert.equal((await a.repository.readEvents(comments.idFor(draft))).length,1);
  passed.push('native new-comment draft adopted with exactly one event');
  await new Promise(resolve => setTimeout(resolve, 300));
  const nodes=await tree.getChildren();
  assert.equal(nodes.length,2);
  const root=nodes.find((node:any)=>node.workspaceKey===folders[0].uri.toString());
  const children=await tree.getChildren(root);
  assert.deepEqual(children.map((node:any)=>node.name), ['src', 'note.txt']);
  const directories=await tree.getChildren(children[0]);
  const nested=await tree.getChildren(directories[0]);
  assert.equal(nested[0].group.documentPath,'src/lib/example.ts');
  assert.equal(tree.getTreeItem(children[0]).command,undefined);
  const node=children.find((node:any)=>node.kind==='document');
  passed.push('Explorer exposes repository, directories and files as navigable tree nodes');
  const command=tree.getTreeItem(node).command;
  assert.ok(command);
  await vscode.window.showTextDocument(b.uri);
  await vscode.commands.executeCommand(command.command,...command.arguments);
  // vscode.open returns after the editor is opened; allow the active-editor event to complete.
  await comments.reloadActive('Explorer click');
  assert.equal(vscode.window.activeTextEditor?.document.uri.toString(),a.uri.toString());
  assert.equal(detail.selected.uri.toString(),a.uri.toString());
  passed.push('multi-root Explorer command opens file and selects details');
  await vscode.commands.executeCommand('sidebandComments.hideResolved');
  assert.ok(!loaded().has(a.resolved.id));
  const leaves = (nodes:any[]):any[] => nodes.flatMap(node => node.kind==='document' ? [node] : leaves(node.children));
  assert.ok(leaves(await tree.getChildren()).every((n:any)=>n.group.threads.every((t:any)=>t.status==='open')));
  await vscode.commands.executeCommand('sidebandComments.showResolved');
  assert.ok(loaded().has(a.resolved.id));
  passed.push('resolved filter updates Explorer and native threads');
  await vscode.window.showTextDocument(b.uri);
  await comments.reloadActive('switch');
  assert.ok(!comments.byDocument.has(a.uri.toString()));
  await vscode.window.showTextDocument(a.uri);
  await comments.reloadActive('return');
  assert.ok(!comments.byDocument.has(b.uri.toString()));
  passed.push('file switches remove stale document threads');
  const hostRepository = comments.workspaceFor(a.uri).repository;
  const read = hostRepository.listByDocument.bind(hostRepository);
  let release!: () => void;
  let started!: () => void;
  const blocked = new Promise<void>(resolve => { release = resolve; });
  const reading = new Promise<void>(resolve => { started = resolve; });
  hostRepository.listByDocument = async (path: string) => {
    const snapshot = await read(path);
    started(); await blocked; return snapshot;
  };
  const pending = comments.load(editor.document, 'delayed read');
  await reading;
  await vscode.window.showTextDocument(b.uri);
  release();
  await pending;
  await comments.reloadActive('after delayed read');
  assert.ok(!comments.byDocument.has(a.uri.toString()));
  hostRepository.listByDocument = read;
  passed.push('delayed read cannot resurrect a document after a file switch');
  await vscode.window.showTextDocument(a.uri);
  await comments.reloadActive('before delayed create');
  const service = comments.workspaceFor(a.uri).service;
  const create = service.create.bind(service);
  let releaseWrite!: () => void;
  let writeStarted!: () => void;
  const writeBlocked = new Promise<void>(resolve => { releaseWrite = resolve; });
  const writing = new Promise<void>(resolve => { writeStarted = resolve; });
  service.create = async (input: any) => {
    const state = await create(input);
    writeStarted(); await writeBlocked; return state;
  };
  const lateDraft = comments.controller.createCommentThread(a.uri,new vscode.Range(2,0,2,17),[]);
  lateDraft.collapsibleState = vscode.CommentThreadCollapsibleState.Collapsed;
  const lateSubmit = comments.submit({thread:lateDraft,text:'save while switching'});
  await writing;
  await vscode.window.showTextDocument(b.uri);
  releaseWrite();
  await lateSubmit;
  assert.ok(!comments.byDocument.has(a.uri.toString()));
  assert.ok((await a.repository.list()).some(thread => thread.comments.some(comment => comment.body === 'save while switching')));
  service.create = create;
  passed.push('save finishing after a file switch persists without restoring stale widgets');
  await writeFile(process.env.SIDEBAND_HOST_RESULT!,JSON.stringify({passed},null,2));
  console.log(JSON.stringify({passed},null,2));
}
